name: envgenerator
description: CLI App to generate environment files
version: 1.0.4
repository: https://github.com/modeckrus/envgenerator

environment:
  sdk: ">=2.17.0 <4.0.0"
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
dependencies:
  json_annotation: ^4.8.0
